### ISSUE TITLE
Roadmap for enclave-cc to support CoCo Key Broker System

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/enclave-cc#120]
### Background

Now enclave-cc uses eaa-kbc & verdictd as underlying attestation & confidential resource broker componant. At the same time, CoCo key broker system is under development. CoCo Key Broker System includes 
- [CC-KBC in Attestation-Agent](https://github.com/confidential-containers/attestation-agent/tree/main/src/kbc_modules/cc_kbc): To collect hardware & software evidence and do remote attestation and make resource request from AS
- [Attestation-Service](https://github.com/confidential-containers/attestation-service): To verify the evidence sent by CC-KBC
- [CC-KBS](https://github.com/confidential-containers/kbs): To distribute confidential resources

Currently, we also use eaa-kbc & verdictd, where
- [eaa-kbc](https://github.com/confidential-containers/attestation-agent/tree/main/src/kbc_modules/eaa_kbc): same functionality as cc-kbc
- [verdictd](https://github.com/inclavare-containers/verdictd): same functionality as AS + CC-KBS

### What we want

To support CoCo key broker system in enclave-cc, we need the following things. Let's make a simple roadmap for this
- [x] Implement Occlum attester in Attestation-agent's cc-kbc
https://github.com/confidential-containers/attestation-agent/issues/134
- [x] Implement SGX verifier in Attestation-Service (As Occlum & Gramine share sgx qvl)
https://github.com/confidential-containers/attestation-service/issues/51
- [x] Add build features for both `attestation-agent/eaa-kbc` and `attestation-agent/cc-kbc` for agent-enclave
- [x] Related tests/ci using coco-key broker system
