### ISSUE TITLE
Roadmap to support new image format for eaa-kbc

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/enclave-cc#130]
As stated https://github.com/confidential-containers/enclave-cc/issues/108, we brought a unified format for encrypted images and a new mechanism to identify kbs resources like decryption keys. We need the following jobs to be done to support the enhancement for encrypted image.

##### For eaa-kbc

- [x] Implement verdictd to support the new resource uri scheme
https://github.com/inclavare-containers/verdictd/issues/29
https://github.com/confidential-containers/attestation-agent/pull/152
- [x] update the image-rs version for enclave-agent
- [x] prepare new test images
https://github.com/confidential-containers/enclave-cc/issues/108
- [x] update ci for eaa-kbc

**Comment by mythi** [comment]
@Xynnn007 thanks for submitting this! For tracking purposes, I was wondering what we need for enclave-cc. The new image format is implicitly supported via #120 and for that we also need #108, right? With that, maybe this issue should just track "support new image format with eaa_kbc in enclave-cc"?

**Comment by Xynnn007** [comment]
> @Xynnn007 thanks for submitting this! For tracking purposes, I was wondering what we need for enclave-cc. The new image format is implicitly supported via #120 and for that we also need #108, right? With that, maybe this issue should just track "support new image format with eaa_kbc in enclave-cc"?

Oh, yes, they are duplicated. Let me fix this
