### ISSUE TITLE
[RFC] Development plan

### ISSUE THREAD

**Issue by jiazhang0** [confidential-containers/enclave-cc#2]
I create this in order to gather the development resources and track the task list. At this moment, IC team from Ali and Intel developers covering container runtime parts will explicitly participate in this project. Also, I‘m glad to add more tasks to detail our works according to the feedback.

# Components

- shim-rune @haosanzi 
- rune and PAL API v4 @YangLiang3, @bigdata-memory
- agent-enclave @YangLiang3 @arronwy @zhiwei-intel-h
- Gramine (including PAL adaption) @ying2liu, @bigdata-memory
- Occlum (including PAL adaption) @qzheng527 
- FUSE encryption fs
- CI/CD

# Milestone 1: Initial PoC

The goal is to enable enclave-cc arch with a LibOS to launch an unencrypted/unsigned hello-world container image. The first LibOS to support this milestone is Occlum. Gramine still needs to discuss about PAL API adaption and decoupling design. 

- [x] agent-enclave supports to pull unencrypted/unsigned image and unpack it as OCI bundle to unprotected storage. @zhiwei-intel-h @YangLiang3 
- [x] the LibOS in app enclave can mount the OCI bundle from unprotected storage as app container rootfs. @zhiwei-intel-h @qzheng527 @YangLiang3 
- [x] shim-rune supports to launch agent-enclave during Pod creation. @haosanzi 
- [x] demo initial enclave-cc PoC based on Occlum (https://github.com/confidential-containers/enclave-cc/issues/8 ) @YangLiang3 @qzheng527 @zhiwei-intel-h @haosanzi 
- [x] draft [local attestation design doc](https://github.com/confidential-containers/enclave-cc/pull/11) describing the protocol between agent-enclave and app-enclave for exchanging the FUSE key. @bigdata-memory 

# Milestone 2: initial code finalization 

The primary goal is to submit and review the initial PoC code base, and enable container image protections.

- [x] import shim-rune (https://github.com/confidential-containers/enclave-cc/issues/4 )  component with a clean base from IC project. @haosanzi @zhiwei-intel-h 
- [ ] integrate ocicrypt-rs to enable the container image decryption support. @intchr @HaokunX-intel @zhiwei-intel-h 
- [ ] enable the image signature verification support. @zhiwei-intel-h
- [ ] documentation works (in documentation repo and this repo).
- [ ] add the basic CI/CD for compilation error check.
- [ ] add the CI/CD runtime test on genuine SGX 2.0 machine for enclave-cc project.

# Milestone 3: attest agent-enclave through remote attestation 

The primary goal is to enable the image protections and E2E demo with remote attestation support.

- [ ] Adapt rats-tls/librats for Gramine LibOS. @vijaydhanraj @ying2liu 
- [ ] enclave-agent as a single process needs to integrate attestation-agent as internal module/service. @jialez0 
- [ ] Finalize the PAL API v4 changes: https://github.com/confidential-containers/enclave-cc/issues/6 @YangLiang3 @ying2liu @bigdata-memory
- [ ] Finalize Occlum PAL API adaption. @qzheng527 
- [ ] Finalize Gramine PAL API adaption (see https://github.com/confidential-containers/enclave-cc/issues/7 for details).  @ying2liu, @bigdata-memory
- [ ] add E2E K8s CI/CD test.
- [ ] add nightly test.

# Milestone 4: initial release

The goal is to accomplish the initial design of enclave-cc, and add operator deployment support for enclave-cc.

- [ ] add CC operator support to deploy enclave-cc.
- [ ] implement that API limiting in enclave-agent.
- [ ] [LA protocol design](https://github.com/confidential-containers/enclave-cc/pull/11) closed. @bigdata-memory 
- [ ] implement the ttrpc client and server for the attested channel used to exchange the decryption key between agent enclave and app enclaves. @YangLiang3 @zhiwei-intel-h @ying2liu @bigdata-memory 
- [ ] provide a build and test script/Makefile to help to develop enclave-cc.
- [ ] rebase shim-rune and rune from IC and upstream. @haosanzi @YangLiang3 
- [ ] enhance CI/CD to cover above new features.

# Follow-up Story

- create the coordination of enclave-cc and kata-cc on Intel CPU, forming the so-called “small TEE and big TEE" similar to "small core and big core", and deploy them together in a node.
- kata-sgx

# Reference

- [enclave-cc design discussion](https://github.com/confidential-containers/documentation/issues/21)
- [enclave-cc design doc PR](https://github.com/confidential-containers/enclave-cc/pull/1)

**Comment by mythi** [comment]
> "enclave-cc v0 PoC"

Just thinking out loud but I wonder if it would make sense to get this work tied to the master project "CCvX" milestones somehow rather than using it's own versioning which is behind the master project. After all there are many components we share.

> import shim-rune and rune components (without commit history) from IC project directly.

Is there some functionality in these we don't need for enclave-CC? IIRC you mentioned the carrier framework stuff isn't necessary. I was wondering would it make sense to clean-up things a bit first?

> the LibOS in app enclave can mount the OCI bundle from unprotected storage as app container rootfs.
> Gramine PAL API adaptation.

We should probably have a task that designs the PAL API changes. Also, this suggests that the milestone criteria is set so that both Occlum and Gramine are supported and validated for each feature. Should that target be made more explicit or we pick only either one for the POCs..

For the "v0" milestone I'd also suggest: all design opens closed.

For a later milestone we need [a task to implement that API limiting](https://github.com/confidential-containers/documentation/issues/21#issuecomment-1060642313).

**Comment by jiazhang0** [comment]
> Just thinking out loud but I wonder if it would make sense to get this work tied to the master project "CCvX" milestones somehow rather than using it's own versioning which is behind the master project. After all there are many components we share.

I try to rename the milestone names but not sure if they are appropriate.

> Is there some functionality in these we don't need for enclave-CC? IIRC you mentioned the carrier framework stuff isn't necessary. I was wondering would it make sense to clean-up things a bit first?
> We should probably have a task that designs the PAL API changes.
> For the "v0" milestone I'd also suggest: all design opens closed.
> For a later milestone we need https://github.com/confidential-containers/documentation/issues/21#issuecomment-1060642313.

Done.

**Comment by jiazhang0** [comment]
I added "Components" and "Follow-up Story".

**Comment by mythi** [comment]
@jiazhang0 thanks!

I'm thinking we could also start moving some of these tasks to "Projects" soon to have better tracking for status.

**Comment by jiazhang0** [comment]
> @jiazhang0 thanks!
> 
> I'm thinking we could also start moving some of these tasks to "Projects" soon to have better tracking for status.

In IC project, I use "projects" to maintain components. So do you also mean this?

**Comment by mythi** [comment]
> > @jiazhang0 thanks!
> > I'm thinking we could also start moving some of these tasks to "Projects" soon to have better tracking for status.
> 
> In IC project, I use "projects" to maintain components. So do you also mean this?

Yes, that was my thinking but instead of doing it for components, we could track milestones.

**Comment by hdxia** [comment]
@jiazhang0, can you add following name to the task list for components and Milestone 1?

> * rune and PAL API v4 @YangLiang3, @Gordon
> * Gramine (including PAL adaption), @Gordon, @Ying

Milestone 1
> * [ ]  designs the PAL API v4 changes. @YangLiang3
> * [ ]  Gramine PAL API adaption, @Gordon, @Ying

**Comment by mythi** [comment]
> I created the first milestone 2022-04 as example. Let me know whether it makes sense to you.

@jiazhang0 looks good!

**Comment by jiazhang0** [comment]
- Move "Gramine PAL API adaption" from the first milestone to the second one.
- It is confirmed that [ying2liu](https://github.com/ying2liu) is the dev and contact from Gramine team.
- It is confirmed that [qzheng527](https://github.com/qzheng527) is the dev and contact from Occlum team.
- The first milestone will use Occlum to show the demo. Gramine adaption (decoupling design) needs to be discussed further.

**Comment by jiazhang0** [comment]
@bigdata-memory Update the detail info for the task "Gramine PAL API adaption".

**Comment by jiazhang0** [comment]
Add "enclave-agent as a single process needs to integrate attestation-agent as internal module/service. " to the second milestone.

**Comment by mythi** [comment]
The containerd 1.7 plans, including the new APIs, were discussed in last week's community call. Since we are still in the very early stages of the implementation, I think we should (re-)think which approach is best for enclave-cc. I'm planning to take a closer look how the 1.7 design for enclave-cc would look. Thoughts on this topic?

**Comment by jiazhang0** [comment]
@mythi Thank you for raising up this. The containerd changes would happen and affect kata-cc as well so eventually we will switch to new approach of containerd if kata-cc decides to follow up it. I guess offloading image pulling to TEE is still a basic principle of CC community so the possible impact is shim api change, which is controllable for enclave-cc.

**Comment by YangLiang3** [comment]
![image](https://user-images.githubusercontent.com/37134635/166459775-c39d1957-5822-463e-8008-d49f138867aa.png)
(Occlum as basic Libos)
What Have Done:
According to the architecture’s steps (mark as completed status by green text )
1.	Completed create and exec agent enclave container based on rune and Occlum(Step 1)
2.	Completed pulling the common image(Step 3)
3.	Completed unpacking image to bundle(Part of Step 5)
4.	Completed mount rootfs and exec User Application(Hardcode fuse key)(Step 8)
5.	Rune PAL API V4 has been submitted to CC community 

What Have Left:
1.	Ttrpc communication between shim-rune and image management  (Intel & Alibaba Co-work) (Step 2)
2.	Setup RA and get the decryption key between Verdictd(KBS) and Attestation Agent (Alibaba) (Step 4)
3.	After getting the decryption key, decrypt the image(Intel) (Part of Step 5)
4.	Get fuse key by LA between agent enclave and App enclave(Intel & Alibaba) (Step 7)
5.	Rune attest command in Rune PAL API V4 is still under discussion.

**Comment by jiazhang0** [comment]
Plan update:
Postpone the following 3 items one month, because it is insufficient to submit the PR on time. Most of efforts are occupied to implement the initial PoC. The design doc of shim-rune would be submitted in the end of this month.
- import shim-rune and rune components with a clean base from IC project. (May to June)
- all design opens closed. (May to June)
- implement that API limiting. (June to July)

**Comment by jiazhang0** [comment]
Update: shim-rune already supports to launch agent-enclave during Pod creation.

**Comment by jiazhang0** [comment]
> > Update: shim-rune already supports to launch agent-enclave during Pod creation.
> 
> @jiazhang0 is this using the pre-created bundle format?

Yes. A pre-created oci bundle for agent-container/enclave is needed because agent-container/enclave is the first component along with pod creation so there is no direct support for it to pull and unpack it in the form of container image in a TEE.

**Comment by zhiwei-intel-h** [comment]
Update： Currently we have completed the first stage of POC that we could use k8s to deploy user app hello-world successfully.
We test the startup time of POD from creating to ready is about 11 seconds, and will optimize it in the future to be less than 10s.

**Comment by jodh-intel** [comment]
@zhiwei-intel-h - Would it be possible to break down that 11 seconds to show where that time is being spent? Presumably most of the time is spent pulling the image, but it would be interesting to understand how the remaining time is divided between the remaining steps (if possible - do the current logs provide sufficient detail I wonder?).

**Comment by mythi** [comment]
> @zhiwei-intel-h - Would it be possible to break down that 11 seconds to show where that time is being spent? 

Also, what's the "baseline" value without enclave-cc in the same environment.

**Comment by mythi** [comment]
> Update： Currently we have completed the first stage of POC 

Let's document the key takeaways from the first milestone: were there unexpected issues that require proper fixing in subsequent milestones. any changes in the design or milestone plans based the learnings?

**Comment by jiazhang0** [comment]
Milestone updates:
- Move the initial PoC demo in cc meeting to June, because the boot time is still long a bit.
- Keep the original goal of June, supporting image protections and remote attestation.

**Comment by YangLiang3** [comment]
@mythi @jodh-intel  we are preparing the time statistics of launch pod and making some optimizations.  Due to the China Dragon Boat Festival, the data will be posted after the holiday. Thanks

**Comment by zhiwei-intel-h** [comment]
shim-rune launch enclave-agent container：
time="2022-06-06T19:01:51.255097194+08:00" level=debug msg="createAgentContainer() end" end time="2022-06-06 19:01:51" name=containerd-shim-v2 source=containerd-rune-shim-v2 start time="2022-06-06 19:01:49" **total time cost=1.45895407s**

shim-rune send request to pull image:
time="2022-06-06T19:01:55.848000611+08:00" level=debug msg="PullImage() end" end time="2022-06-06 19:01:55" name=containerd-shim-v2 source=containerd-rune-shim-v2 start time="2022-06-06 19:01:51" **total time cost=4.56953493s**

shim-rune launch app-container：
time="2022-06-06T19:01:56.611420379+08:00" level=debug msg="create App Container() end" end time="2022-06-06 19:01:56" name=containerd-shim-v2 source=containerd-rune-shim-v2 start time="2022-06-06 19:01:55" **total time cost=753.127063ms**

**Comment by ariel-adam** [comment]
@jiazhang0 is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by mythi** [comment]
> @jiazhang0 is this issue still relevant or can be closed?

@jiazhang0 I think most of the items originally covered by this plan are now complete. Maybe we can close this and track any remaining items in their own issues?
