### ISSUE TITLE
improve payload image creation

### ISSUE THREAD

**Issue by mythi** [confidential-containers/enclave-cc#45]
Current payload image tooling in `tools/packaging` was drafted fairly quickly before the release and there few improvement areas:

- [x] build `shim-rune` in a container (#68)
- [ ] build `agent-enclave` by `COPY`ing the code rather than `git clone`ing (#69 )
- [x] move `init` maintenance to this repo (#43)
- [ ] build `init` by `COPY`ing the code rather than `git clone`ing (#69 )

**Comment by HaokunX-intel** [comment]
The script `tools/build/agent-enclave-build/gen_bundle.sh` is aimed at building the agent bundle, if we want to reuse it for development debugging, I think there are some gaps on parameter tunning,
-  decoupling "SIM/HW" and "debuggable = true/false" [here](https://github.com/confidential-containers/enclave-cc/blob/c9ab4f08cfcd7afdb66c93956150e71de6225446/tools/packaging/build/agent-enclave-bundle/jq.filter#L6): we need to get more logs when the agent runs on the "HW" mode;
- customizing more parameters in the Occlum.json: parameters in occlum.json may need to be tunned for new features;
- printing out more logs [here](https://github.com/confidential-containers/enclave-cc/blob/c9ab4f08cfcd7afdb66c93956150e71de6225446/tools/packaging/build/agent-enclave-bundle/config.json.template#L17): env variables `OCCLUM_LOG_LEVEL=trace` and `OCCLUM_RELEASE_ENCLAVE=0` need to be appended in the `config.json`

And bundle building steps are in a container, developers can not dive inside them to see more details . We need to provide more materials to ease debugging,
- exporting some intermediate products: for example, the `occlum_instance` can be exported before it is packaged. We can check if any necessary files, libs or so on have be copied into the current place. Furthermore, directly launch the agent by `occlum-run`.
- caching repetitive container layers: it consumes too much time to build a container from scratch.

From my opinion, the `tools/build/agent-enclave-build/gen_bundle.sh` is a succinct script for deployment in the product env, if we make it satisfy all above demands from the development env, the script will be bloated and complicated.  

Should we keep two scripts for different purposes? And update the deploy scripts if necessary.

**Comment by mythi** [comment]
@HaokunX-intel that's good feedback. 

> Should we keep two scripts for different purposes? And update the deploy scripts if necessary.

The problem with this approach (based on what's in PR #67) is that they give totally different environments. If something works for developers using version XYZ Occlum/SGXSDK/DCAP installed on the host, things may (likely will) fail with the setup installed with `tools/build/agent-enclave-build/gen_bundle.sh`. 

> And bundle building steps are in a container, developers can not dive inside them to see more details 

I think the right approach is to document how developers can copy custom Occlum instances to the pre-installed bundle. `config.json` modifications can be made manually by developers.

**Comment by hairongchen** [comment]
I'd suggest we split PR https://github.com/confidential-containers/enclave-cc/pull/48 and add one task in this issue to track  adding rats-tls into enclave-agent in build process, as rats-tls is needed by EAA+Verdictd(required in CI cases https://github.com/confidential-containers/enclave-cc/issues/13#issuecomment-1333052367)

@jiere @mythi

**Comment by mythi** [comment]
@hairongchen works for me

**Comment by jiere** [comment]
@mythi , just updated this thread, PR#69 raised for two task items above. Please help review it.
For PR#68, I have added some minor comments, pls check and close it soon, thanks.
The PR#48 split job will be done later.

**Comment by hairongchen** [comment]
add one more task to this list: build rats-tls into enclave agent container image bundle

**Comment by jiere** [comment]
I would suggest to move the current two "TBC" task items to other issue, and close current issue in 0.3.0 release.

**Comment by mythi** [comment]
> add one more task to this list: build rats-tls into enclave agent container image bundle

I'd propose we don't overload this issue with any items that contribute to new features.
